auth:
  adminUser: admin
  adminPassword: randomchangeme

ingress:
  enabled: true
  hostname: "{{ lb_public_domain_name }}"
  path: /keycloak-auth

metrics:
  enabled: true

postgresql:
  enabled: true
  postgresqlPassword: randomchangeme2
