extraEnv: |
  - name: KEYCLOAK_LOGLEVEL
    value: DEBUG
  - name: KEYCLOAK_USER
    value: admin
  - name: KEYCLOAK_PASSWORD
    value: randomchangeme
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"

postgresql:
  enabled: true
  postgresqlPassword: randomchangeme2
