image:
  registry: registry.hpc.ut.ee/mirror
  repository: bitnami/keycloak

auth:
  adminPassword: randomchangeme

service:
  type: ClusterIP

ingress:
  enabled: true
  hostname: "{{ lb_public_domain_name }}"
  path: /keycloak-auth

metrics:
  enabled: true

postgresql:
  enabled: true
  auth:
    postgresPassword: randomchangeme2
