# -*- coding: utf-8; indent-tabs-mode: nil; tab-width: 2; -*-

---
- name: Setup ssh keys
  become: yes
  hosts: rke2_nodes
  vars_files:
    - rke2_vars.defaults
    - rke2_vars.custom
  roles:
    - ssh_admin
