- name: Setup Waldur and supporting applications
  hosts: "{{ host_group | default('rke2_nodes') }}"
  become: true
  vars_files:
    - rke2_vars.defaults
    - rke2_vars.custom
  tasks:
    - name: Selecting initial server from inventory
      set_fact:
        initial_server: "{{ hostvars.values() | selectattr('initial_server', 'defined') }}"

    - debug:
        msg: "{{ initial_server[0].ansible_host }} {{ initial_server[0].inventory_hostname }}"

    - name: Setup Keyclaok
      import_tasks: task-files/keycloak-installation.yaml
      when:
        - setup_keycloak | default(true)
        - inventory_hostname == initial_server[0].inventory_hostname

    - name: Setup k8s dashboard
      import_tasks: task-files/k8s-dashboard-setup.yaml
      when:
        - setup_k8s_dashboard | default(true)
        - initial_server | default(false) | bool

    - name: Setup Loki, Grafana, Prometheus
      import_tasks: task-files/loki-installation.yaml
      when:
        - setup_loki_prom_grafana | default(true)
        - initial_server | default(false) | bool

    - name: Setup LetsEncrypt
      import_tasks: task-files/letsencrypt-installation.yaml
      when:
        - setup_lets_encrypt | default(true)
        - initial_server | default(false) | bool

    - name: Setup MinIO
      import_tasks: task-files/minio-installation.yaml
      when:
        - setup_minio | default(true)
        - initial_server | default(false) | bool

    - name: Setup Waldur
      import_tasks: task-files/waldur-installation.yaml
      when:
        - setup_waldur | default(true)
        - initial_server | default(false) | bool
