- name: Setup Waldur and supporting applications
  hosts: "{{ host_group | default('rke2_nodes') }}"
  become: true
  vars_files:
    - rke2_vars
  tasks:
    - name: Setup k8s dashboard
      import_tasks: task-files/k8s-dashboard-setup.yaml
      when:
        - setup_k8s_dashboard | default(true)
        - initial_server | default(false) | bool

    - name: Setup Loki, Grafana, Prometheus
      import_tasks: task-files/loki-installation.yaml
      when:
        - setup_loki_prom_grafana | default(true)
        - initial_server | default(false) | bool

    - name: Setup LetsEncrypt
      import_tasks: task-files/letsencrypt-installation.yaml
      when:
        - setup_lets_encrypt | default(true)
        - initial_server | default(false) | bool

    - name: Setup PostgreSQL
      import_tasks: task-files/postgresql-installation.yaml
      when:
        - setup_postgresql | default(true)
        - initial_server | default(false) | bool

    - name: Setup RabbitMQ
      import_tasks: task-files/rabbitmq-installation.yaml
      when:
        - setup_rabbitmq | default(true)
        - initial_server | default(false) | bool

    - name: Setup MinIO
      import_tasks: task-files/minio-installation.yaml
      when:
        - setup_minio | default(true)
        - initial_server | default(false) | bool

    - name: Setup Waldur
      import_tasks: task-files/waldur-installation.yaml
      when:
        - setup_waldur | default(true)
        - initial_server | default(false) | bool
