- name: Setup RKE2 node with Longhorn and Waldur
  hosts: "{{ host_group | default('rke2_nodes') }}"
  become: true
  vars_files:
    - rke2_vars
  tasks:
    - name: Get environment
      shell: env
      environment: "{{ proxy_env | default({}) }}"
      register: env

    - name: Print environment
      run_once: true
      ansible.builtin.debug:
        msg: "{{ env.stdout }}"

    - name: Setup disk for storage
      import_tasks: task-files/disk-setup.yaml
      when: setup_storage | default(true)

    - name: Setup RKE2
      import_tasks: task-files/rke2-setup.yaml
      when: setup_rke2 | default(true)

    - name: Setup Helm
      import_tasks: task-files/helm-installation.yaml
      when: setup_helm | default(true)

    - name: Setup Longhorn
      import_tasks: task-files/longhorn-setup.yaml
      when: setup_longhorn | default(true)

    - name: Setup k8s dashboard
      import_tasks: task-files/k8s-dashboard-setup.yaml
      when: setup_k8s_dashboard | default(true)

    - name: Setup Waldur
      import_tasks: task-files/waldur-installation.yaml
      when: setup_waldur | default(true)
