- name: Update Waldur release
  hosts: "{{ host_group | default('rke2_nodes') }}"
  become: true
  vars_files:
    - rke2_vars
  tasks:
    - name: Setup Waldur
      import_tasks: task-files/waldur-installation.yaml
      when: setup_waldur | default(true)
